// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeminjamanRuanganAPI.Data;

#nullable disable

namespace PeminjamanRuangan.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213120802_AddSeeders")]
    partial class AddSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.BookingStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomBookingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomBookingId");

                    b.ToTable("BookingStatusHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTime(2026, 1, 1, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            ChangedByUserId = 2,
                            NewStatus = "Pending",
                            OldStatus = "Pending",
                            RoomBookingId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTime(2026, 1, 1, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            ChangedByUserId = 2,
                            NewStatus = "Pending",
                            OldStatus = "Pending",
                            RoomBookingId = 2
                        });
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Description = "Ruang kelas",
                            IsActive = true,
                            Location = "Gedung D3, LT. 2",
                            Name = "HH-203"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            Description = "Ruang kelas",
                            IsActive = true,
                            Location = "Gedung SAW, LT. 6",
                            Name = "SAW-06.06"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 120,
                            Description = "Ruang kelas",
                            IsActive = true,
                            Location = "Gedung SAW, LT. 7",
                            Name = "SAW-07.10"
                        });
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.RoomBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomBookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Diskusi Tugas Akhir",
                            RoomId = 1,
                            StartTime = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2024, 7, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Purpose = "Seminar Proyek",
                            RoomId = 3,
                            StartTime = new DateTime(2024, 7, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@campus.com",
                            PasswordHash = "$2a$11$ec/jgyW.C8Q61nprj0IvVesMTiFyg3eaF0hMc/eNSo1PaWIR6uPiC",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@campus.com",
                            PasswordHash = "$2a$11$Op6pjkCaU.9FkqNrtWkJ2OpWe/FE8f5urbgfPZhZRaP8d5743/eUu",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.BookingStatusHistory", b =>
                {
                    b.HasOne("PeminjamanRuanganAPI.Models.RoomBooking", "RoomBooking")
                        .WithMany("StatusHistories")
                        .HasForeignKey("RoomBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomBooking");
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.RoomBooking", b =>
                {
                    b.HasOne("PeminjamanRuanganAPI.Models.Room", "Room")
                        .WithMany("RoomBookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeminjamanRuanganAPI.Models.User", "User")
                        .WithMany("RoomBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.Room", b =>
                {
                    b.Navigation("RoomBookings");
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.RoomBooking", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("PeminjamanRuanganAPI.Models.User", b =>
                {
                    b.Navigation("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
